### ISSUE TITLE
What is the best way to open as modal view

### ISSUE THREAD

**Issue by vikmeup** [uacaps/CAPSPhotoView#1]
Can you make a support of opening imageView in UIViewController.

**Comment by fahlout** [comment]
I will work on adding the functionality of opening the photo view as a modal view as soon as the core functionality of this project is stable. This project is still in its early stages though.

**Comment by fahlout** [comment]
modal functionality has been added. I need to work on performance though.

**Comment by vikmeup** [comment]
You guys awesome! I will test it out tonight.

**Comment by fahlout** [comment]
Let me know if it is the functionality you were looking for. There is still a lot of room for improvement and I am still actively working to get to a release ready version.
