### ISSUE TITLE
iPhone 4, not showing title, subtitle, date

### ISSUE THREAD

**Issue by vikmeup** [uacaps/CAPSPhotoView#12]
![ios simulator screen shot apr 24 2014 11 07 18 pm](https://cloud.githubusercontent.com/assets/1641795/2797848/d77a19b2-cc3f-11e3-9e04-b9f49ddf775f.png)

**Comment by isayeter** [comment]
![ios simulator screen shot 25 apr 2014 15 58 23](https://cloud.githubusercontent.com/assets/3602109/2800792/5afa6bb4-cc79-11e3-952c-c71e675109aa.png)

you are right, bottom screen is not shown, also after some clicks event done button is disappearing too.

**Comment by isayeter** [comment]
![ios simulator screen shot 25 apr 2014 16 18 06](https://cloud.githubusercontent.com/assets/3602109/2800993/1ce97380-cc7c-11e3-971d-a9dfab0f28c1.png)

in iPad everything is going to crazy.

**Comment by fahlout** [comment]
that is an autoresizing issue i will be working on
