### ISSUE TITLE
Animation not Smooth

### ISSUE THREAD

**Issue by vikmeup** [uacaps/CAPSPhotoView#2]
https://www.youtube.com/watch?v=LiQ1aG34BDY&feature=youtu.be

Xcode 5.1 and iOS 7.1

**Comment by fahlout** [comment]
I will look into what might be causing this

**Comment by vikmeup** [comment]
it could be affected by Navigation Bar. 
I tried to add 60px to originSize of Photo, and it worked smoothly.

**Comment by fahlout** [comment]
It might also be the header in your table view cells. Is that also 60px tall?

**Comment by vikmeup** [comment]
I'm not using header in table view. 
It's custom cell with UIView, which is ~50px tall.

**Comment by fahlout** [comment]
For now please add 60px to originSize, as that seems to work for you, until I get around to fixing it properly. Thanks.

**Comment by fahlout** [comment]
this issue should be fixed now
